### PR TITLE
Update main init for long range correction to energy and pressure

### PR DESCRIPTION
**Pull request by justinGilmer**

### CODE REVIEW

**Comment by justinGilmer** [comment]
A lot of the changes had been made before, but can a few check these changes and the full file to make sure I did not miss anything?

**Comment by justinGilmer** [comment]
Actaully, ignore my comment. This is handled in azurepipelines already.

**Review by jennyfothergill — APPROVED** [review]
LGTM!

**Review by bc118 — APPROVED** [review]
These changes look good to me.  The box size changes for water and ethanol where apparently already done.

**Pull request merged**
